import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Intro from './sections/intro';
import Bg from './sections/bg';
import { Container, Flex, VStack } from '@chakra-ui/react';
import Particles from "react-tsparticles";
import Projects from './sections/projects';
import { motion } from 'framer-motion';

const Home: NextPage = () => {
 
  return (
    <>
      <Head>
          <meta name="title" content="Akshat Agrawal" />
          <meta name="description" content="Akshat Agrawal" />
          <meta property="og:type" content="website" />
          <meta property="og:title" content="Akshat Agrawal" />
          <meta property="og:description" content="Akshat Agrawal" />
          <meta property="twitter:card" content="summary_large_image" />
          <meta property="twitter:title" content="Akshat Agrawal" />
          <meta property="twitter:description" content="Akshat Agrawal" />
          <title>Akshat Agrawal</title>
      </Head>
      <motion.div
        animate={{
            opacity: [0, 1]
        }}
        transition={{
            duration: 0.5,
            delay: 0.25
        }}
      >
        <Particles
              options={{
                fullScreen: {
                  enable: true,
                  zIndex: 0
                },
                particles: {
                  number: {
                    value: 25,
                    limit: 300,
                    density: {
                      enable: true,
                      value_area: 800
                    }
                  },
                  color: {
                    value: "#ffffff"
                  },
                  opacity: {
                    value: 0.5,
                    random: true,
                    anim: {
                      enable: true,
                      speed: 1,
                      opacity_min: 0.5,
                      sync: false
                    }
                  },
                  size: {
                    value: 5,
                    random: true,
                    anim: {
                      enable: true,
                      speed: 2,
                      size_min: 1,
                      sync: false
                    }
                  },
                  line_linked: {
                    enable: true,
                    distance: 100,
                    color: "#ffffff",
                    opacity: 1,
                    width: 1
                  },
                  move: {
                    enable: true,
                    speed: 0.5,
                    direction: "none",
                    random: false,
                    straight: false,
                    out_mode: "out",
                    bounce: false,
                    attract: {
                      enable: false,
                      rotateX: 600,
                      rotateY: 1200
                    }
                  }
                },
                retina_detect: true,
                fps_limit: 60
              }}
        />
      </motion.div>
      <Intro></Intro>
      <Projects></Projects>
    </>

  )
}

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

export default Home;
